"""Category table Create

Revision ID: 590613b1db10
Revises: 8e29cc9885a9
Create Date: 2026-02-18 02:09:36.776937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590613b1db10'
down_revision: Union[str, None] = '8e29cc9885a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_category_uid'), 'category', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_uid'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###