"""Create Product Model

Revision ID: c7fa0fce17ad
Revises: fd5bdbbc7bc6
Create Date: 2026-02-21 15:49:09.039124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7fa0fce17ad'
down_revision: Union[str, None] = 'fd5bdbbc7bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###