"""Create Product Model

Revision ID: fd5bdbbc7bc6
Revises: 590613b1db10
Create Date: 2026-02-21 15:17:36.209786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5bdbbc7bc6'
down_revision: Union[str, None] = '590613b1db10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_product_uid'), 'product', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_uid'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###